title: neochoon's essays
description: Critical takes on AI tools, developer workflows, and modern software.
baseurl: 
repository: neochoon/essays
url: "https://neochoon.github.io"
author: ChoonSik C.
theme: minima
future: true
